# This workflow will build the python documentation from source code
#   and publish it to GitHub Pages (on gh-pages branch)


name: Build and Deploy GitHub Page

on:
  push:
    branches: [master]

jobs:
  deploy-docs:
    #needs: run_tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: build docs
        run: |
          pdoc3 --html osbot_utils --html-dir=docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages          # The branch the action should deploy to.
          FOLDER: docs/osbot_utils  # The folder the action should deploy.