name: "gh-pages__deploy-mkdocs"
description: "gh-pages__deploy-mkdocs"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install MkDocs
      shell: bash
      run: pip install mkdocs

    - name: Deploy Documentation
      shell: bash
      run: mkdocs gh-deploy --force