name: Run Python Tests
description: 'Run Python Tests'

inputs:
  codecov_token:
    description: 'CodeCov access token'
    required: true
  package_name:
    description: 'Package name for coverage'
    required: true

runs:
    using: 'composite'
    steps:
      - name: Install poetry dependencies (again)
        shell: bash
        run: |
          ls $HOME
          ls $HOME/.local/bin
          pwd
          export PATH="$HOME/.local/bin:$PATH"
          poetry install
          poetry check
          poetry show
      - name: Run tests with pytest (with coverage)
        shell: bash
        run: |     
          pytest -v -s --durations=0 tests
          coverage run --source=${{ inputs.package_name }} -m pytest -v -s --durations=0 --ignore=tests_* tests
      - name: Print coverage report
        shell: bash
        run: |
          coverage report -m
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN         : ${{ inputs.codecov_token         }}