lines = ['html (lang="en")',
         '    ├── head\n'
         '    │   ├── meta (charset="UTF-8")\n'
         '    │   ├── meta (name="viewport" content="width=device-width, initial-scale=1.0")\n'
         '    │   ├── title\n'
         '    │   │   └── TEXT: Simple Bootstrap 5 Webpage\n'
         '    │   └── link (href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous")',
         '    └── body\n'
         '        ├── nav (class="navbar navbar-expand-lg navbar-dark bg-dark")\n'
         '        │   └── div (class="container-fluid")\n'
         '        │       ├── a (class="navbar-brand" href="#")\n'
         '        │       │   └── TEXT: Webpage Name\n'
         '        │       ├── button (class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation")\n'
         '        │       │   └── span (class="navbar-toggler-icon")\n'
         '        │       └── div (class="collapse navbar-collapse" id="navbarNav")\n'
         '        │           └── ul (class="navbar-nav")\n'
         '        │               ├── li (class="nav-item")\n'
         '        │               │   └── a (class="nav-link active" aria-current="page" href="#")\n'
         '        │               │       └── TEXT: Home\n'
         '        │               ├── li (class="nav-item")\n'
         '        │               │   └── a (class="nav-link" href="#")\n'
         '        │               │       └── TEXT: Features\n'
         '        │               ├── li (class="nav-item")\n'
         '        │               │   └── a (class="nav-link" href="#")\n'
         '        │               │       └── TEXT: Pricing\n'
         '        │               └── li (class="nav-item")\n'
         '        │                   └── a (class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true")\n'
         '        │                       └── TEXT: Disabled\n'
         '        ├── div (class="p-5 mb-4 bg-light rounded-3")\n'
         '        │   └── div (class="container-fluid py-5")\n'
         '        │       ├── h1 (class="display-5 fw-bold")\n'
         '        │       │   └── TEXT: Welcome to Our Website!\n'
         '        │       ├── p (class="col-md-8 fs-4")\n'
         '        │       │   └── TEXT: This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.\n'
         '        │       └── button (class="btn btn-primary btn-lg" type="button")\n'
         '        │           └── TEXT: Example button\n'
         '        ├── footer (class="py-3 my-4")\n'
         '        │   ├── ul (class="nav justify-content-center border-bottom pb-3 mb-3")\n'
         '        │   │   ├── li (class="nav-item")\n'
         '        │   │   │   └── a (href="#" class="nav-link px-2 text-muted")\n'
         '        │   │   │       └── TEXT: Home\n'
         '        │   │   ├── li (class="nav-item")\n'
         '        │   │   │   └── a (href="#" class="nav-link px-2 text-muted")\n'
         '        │   │   │       └── TEXT: Features\n'
         '        │   │   ├── li (class="nav-item")\n'
         '        │   │   │   └── a (href="#" class="nav-link px-2 text-muted")\n'
         '        │   │   │       └── TEXT: Pricing\n'
         '        │   │   ├── li (class="nav-item")\n'
         '        │   │   │   └── a (href="#" class="nav-link px-2 text-muted")\n'
         '        │   │   │       └── TEXT: FAQs\n'
         '        │   │   └── li (class="nav-item")\n'
         '        │   │       └── a (href="#" class="nav-link px-2 text-muted")\n'
         '        │   │           └── TEXT: About\n'
         '        │   └── p (class="text-center text-muted")\n'
         '        │       └── TEXT: © 2023 Company, Inc\n'
         '        └── script (src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous")']

