name       : CI Pipeline - DEV
on:
  push:
    branches:
      - dev

env:
  GIT__BRANCH  : 'dev'
  PACKAGE_NAME : 'osbot_utils'
  RELEASE_TYPE : 'minor'

jobs:

  run-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9.21, 3.10.16, 3.11.11, 3.12.8, 3.13.1 ]
                        #[  3.8.18, 3.9.19, 3.10.14, 3.11.9, 3.12.3 , ]
                        # [3.7.17, 3.13.0-beta.1 ] # poetry doesn't support: 3.7.17, and was hanging on the installation of 3.13.0-beta.1

    steps:
      - uses: actions/checkout@v4
      - name: Run Unit Tests (using Pytest)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pytest__run-tests@dev

  increment-tag:
    name: Increment Tag - DEV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag (for DEV)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type: ${{env.RELEASE_TYPE}}
    needs:
      - run-unit-tests

  deploy-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy MKDocs to GH Static Pages
        uses: ./.github/actions/gh-pages__deploy-mkdocs
    needs:
      - increment-tag

