name       : CD Pipeline - MAIN
on:
  push:
    branches:
      - main


env:
  GIT__BRANCH         : 'main'
  PACKAGE_NAME        : 'osbot_utils'
  RELEASE_TYPE        : 'major'

jobs:

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Unit Tests (using Pytest)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pytest__run-tests@dev

  increment-tag:
    name: Increment Tag - MAIN
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Increment Tag (for MAIN)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type: ${{env.RELEASE_TYPE}}
    needs:
      - run-unit-tests

  publish-to-pypi:
    permissions:
      id-token: write
    name: "Publish to PYPI"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Git Update Current Branch
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__update_branch@dev

      - name: publish-to-pypi
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pypi__publish@dev
    needs:
      - increment-tag

  deploy-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy MKDocs to GH Static Pages
        uses: ./.github/actions/gh-pages__deploy-mkdocs
    needs:
      - increment-tag

