name: Build and Push Docker Image

#on:
#  push:

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Increment Tag - Main branch"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN    }}

#      - name: Build and push Docker image (diniscruz/osbot_utils:latest)
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: ./docker/python_slim/Dockerfile
#          push: true
#          tags: diniscruz/osbot_utils:latest
#
#      - name: Build and push Docker image (diniscruz/osbot_utils:latest-pyodide)
#        uses: docker/build-push-action@v5
#        with:
#          context: ./docker/pyodide/web/
#          file: ./docker/pyodide/web/Dockerfile
#          push: true
#          tags: diniscruz/osbot_utils:latest-pyodide

      - name: Build and push Docker image (diniscruz/python_with_ssh:latest)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/python_with_ssh/Dockerfile
          push: true
          tags: diniscruz/python_with_ssh:latest