name: Publish to PyPI

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Increment Tag - Main branch"]
    types:
      - completed

permissions:
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/publish-to-pypi@main
        with:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}