name       : Run Tests - Unit
on:
  push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13]

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies (using Pip)
        uses: ./.github/actions/install-dependencies-pytest
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Unit Tests
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/run-unit-tests@main
        with:
          package_name          : 'osbot_utils'
          codecov_token         : ${{ secrets.CODECOV_TOKEN          }}
